export const PHRENOLOGIE_CONFIG = {
  torch: {
    size:              0.22,
    grow_duration:     6000,
    fade_out_duration: 1500,
  },
  arrow: {
    appear_at:     5500,
    draw_duration: 2200,
  },
  docs: {
    appear_at:     6000,
    width_vw:        16,
    height_vh:        7,
    width_min:      120,
    width_max:      280,
    height_min:      36,
    height_max:      90,
    draw_duration:  850,
    labels:  ['Document 1', 'Document 2', 'Document 3', 'Document 4'],
    actions: [null, null, null, null] as (string | null)[],
  },
  navbar: {
    appear_at:          7000,
    width:              0.80,
    bottom:             0.05,
    height:             0.08,
    stroke_color:       'rgba(255,255,255,0.80)',
    stroke_width:        0.8,
    draw_speed:          1.4,
    sep_speed:           0.5,
    sep_delay:           0.3,
    text_delay:          0.25,
    text_fade:           0.4,
    btn_color:          'rgba(255,255,255,0.85)',
    btn_color_hover:    'rgba(255,220,120,1)',
    btn_letter_spacing: '0.18em',
    labels:  ['Carnet de Recherche', 'Collaboration', 'À Propos'],
    actions: [null, 'collaboration', null] as (string | null)[],
  },
  timing: {
    bg_fade_in:          1200,
    pause_before_torch:   500,
    exit_black_pause:      10,
  },
} as const